name: lensing
channels:
  - pytorch
  - https://conda.anaconda.org/NLeSC
  - defaults
dependencies:
  - appnope=0.1.0
  - astropy=3.1.2
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - backcall=0.1.0
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2018.11.29
  - cffi=1.11.5
  - cycler=0.10.0
  - decorator=4.3.2
  - freetype=2.9.1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - jedi=0.13.2
  - jpeg=9b
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.36
  - libsodium=1.0.16
  - libtiff=4.0.10
  - matplotlib=3.0.2
  - mkl=2019.1=144
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=5.0.0
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1b
  - parso=0.3.2
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.4.1
  - pip=19.0.1
  - pluggy=0.8.1
  - prompt_toolkit=2.0.8=py_0
  - psutil=5.5.0
  - ptyprocess=0.6.0
  - py=1.7.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pytest=4.2.0
  - pytest-arraydiff=0.3
  - pytest-astropy=0.5.0
  - pytest-doctestplus=0.2.0
  - pytest-openfiles=0.3.2
  - pytest-remotedata=0.3.1
  - python=3.6.8
  - python-dateutil=2.7.5
  - pytz=2018.9
  - pyzmq=17.1.2
  - readline=7.0
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - setuptools=40.7.3
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - tornado=5.1.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - wheel=0.32.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
  - pytorch=1.0.1
  - torchvision=0.2.1
  - pip:
    - appdirs==1.4.3
    - autograd==1.2
    - black==18.9b0
    - click==7.0
    - future==0.16.0
    - pkginfo==1.4.2
    - pybind11==2.2.1
    - readme-renderer==24.0
    - requests-toolbelt==0.8.0
    - toml==0.10.0
    - torch==1.0.1.post2
    - twine==1.12.1
    - uproot==2.8.33
